import type { BookingCase } from './domain/types'

export const BOOKING_MASTER_COLUMNS = [
  'caseId',
  'version',
  'status',
  'formResponseId',
  'adminId',
  'adminName',
  'submitterEmail',
  'adminIdentityStatus',
  'aeId',
  'aeName',
  'customerName',
  'customerNameNormalized',
  'phoneNormalized',
  'phoneMasked',
  'doctorId',
  'serviceId',
  'channelId',
  'appointmentStart',
  'appointmentEnd',
  'depositAmount',
  'depositReceivedAt',
  'depositExpiresAt',
  'depositStatus',
  'driveFolderId',
  'driveFolderUrl',
  'paymentEvidenceCount',
  'chatEvidenceCount',
  'calendarId',
  'calendarEventId',
  'doctorLineGroupId',
  'doctorLineNotifiedAt',
  'callStatus',
  'firstCallWindowStart',
  'firstCallWindowEnd',
  'nextCallAt',
  'lastCallAt',
  'callOwnerAdminId',
  'jeraPaymentId',
  'jeraStatus',
  'jeraClosedAt',
  'jeraActualRevenue',
  'jeraImportFileId',
  'reconciliationStatus',
  'commissionEligibility',
  'commissionAmount',
  'driveState',
  'calendarState',
  'lineState',
  'jeraImportState',
  'createdAt',
  'createdBy',
  'updatedAt',
  'updatedBy',
] as const satisfies readonly (keyof BookingCase)[]

export const SHEET_SCHEMAS: Record<string, readonly string[]> = {
  FORM_RESPONSES: [],
  BOOKING_MASTER: BOOKING_MASTER_COLUMNS,
  CALL_QUEUE: ['taskId', 'caseId', 'ownerAdminId', 'status', 'windowStart', 'windowEnd', 'nextCallAt', 'lastReminderDate', 'result', 'note', 'version'],
  JERA_IMPORT_RAW: ['importId', 'fileId', 'paymentId', 'date', 'time', 'customerNameNormalized', 'phoneNormalized', 'status', 'actualRevenue', 'importedAt'],
  JERA_IMPORT_FILES: ['fileId', 'hash', 'status', 'transactionCount', 'rejectedCount', 'importedAt', 'safeError'],
  RECONCILIATION: ['id', 'source', 'sourceId', 'reasonCode', 'candidateCaseIds', 'status', 'resolvedCaseId', 'resolvedBy', 'resolvedAt', 'version'],
  RETRY_QUEUE: ['id', 'caseId', 'operation', 'idempotencyKey', 'attempts', 'nextAttemptAt', 'status', 'safeError', 'payload'],
  CONFIG_ADMINS: ['id', 'name', 'email', 'lineUserId', 'active'],
  CONFIG_STAFF: ['id', 'name', 'email', 'lineUserId', 'canCloseBooking', 'canBeAe', 'active'],
  CONFIG_DOCTORS: ['id', 'name', 'calendarId', 'lineGroupId', 'active'],
  CONFIG_SERVICES: ['id', 'name', 'durationMinutes', 'active'],
  CONFIG_CHANNELS: ['id', 'name', 'active'],
  CONFIG_RULES: ['key', 'value', 'updatedAt', 'updatedBy'],
  CONFIG_LINE_DIRECTORY: ['sourceType', 'sourceId', 'capturedAt', 'alias'],
  LINE_INGRESS_NONCES: ['nonce', 'capturedAt'],
  FORM_RESPONSE_MAP: ['formResponseId', 'caseId'],
  SYSTEM_SEQUENCES: ['month', 'sequence'],
  RETENTION_QUEUE: ['id', 'caseId', 'eligibleAt', 'status', 'approvedBy', 'approvedAt', 'reason', 'version'],
  AUDIT_LOG: ['eventId', 'caseId', 'actor', 'action', 'target', 'before', 'after', 'reason', 'timestamp', 'correlationId'],
  DASHBOARD: [],
}
